# Generated by Django 5.0.6 on 2025-06-26 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for this post", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The generated social media content"),
                ),
                (
                    "original_prompt",
                    models.TextField(
                        help_text="The original user prompt that generated this content"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "conversation_history",
                    models.JSONField(
                        blank=True,
                        help_text="Full conversation history from the generation process",
                        null=True,
                    ),
                ),
                (
                    "generation_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata about the generation process",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Draft",
                "verbose_name_plural": "Post Drafts",
                "ordering": ["-created_at"],
            },
        ),
    ]
